version: '2'

services:
  web:
    image: releasepraqma/sentence:latest
    command: --age-service http://age:8080 --name-service http://name:8080
    ports: 
      - 8080:8080
    # platform: linux/arm64/v8
  name:
    image: releasepraqma/name:latest
    # platform: linux/arm64/v8
  age:
    image: releasepraqma/age:latest
    # platform: linux/arm64/v8