sentences:
  replicas: 1
  image:
    repository: releasepraqma/sentence
    tag: latest
  service:
    type: NodePort
    name: sentence
    port: 9090
  resources:
    requests:
      cpu: 0.25
    limits:
      cpu: 0.25
