apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    managed_by: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
  - name: server
    port: 80 # Service port
    targetPort: {{ .Values.containerPort }}
